### ISSUE TITLE
Error stopping the plugin from installing

### ISSUE THREAD

**Issue by rhysmerritt** [cdes/figma-plugin-manager-desktop#8]
```
Error: EPERM: operation not permitted, unlink '/Users/rhysmerritt/Library/Application Support/Figma Plugins Desktop Injector/input'
    at fs.unlinkSync (fs.js:1061:3)
    at startInjecting (/private/var/folders/z4/b157rzm93qb1g6fvrszxlhvr0000gn/T/AppTranslocation/F7CD8D13-C442-4794-A067-A3275C268586/d/Figma Plugins Desktop Injector.app/Contents/Resources/app.asar/renderer.js:206:29)
    at dialog.showMessageBox (/private/var/folders/z4/b157rzm93qb1g6fvrszxlhvr0000gn/T/AppTranslocation/F7CD8D13-C442-4794-A067-A3275C268586/d/Figma Plugins Desktop Injector.app/Contents/Resources/app.asar/renderer.js:159:9)
    at CallbacksRegistry.apply (/private/var/folders/z4/b157rzm93qb1g6fvrszxlhvr0000gn/T/AppTranslocation/F7CD8D13-C442-4794-A067-A3275C268586/d/Figma Plugins Desktop Injector.app/Contents/Resources/electron.asar/common/api/callbacks-registry.js:47:25)
    at EventEmitter.ipcRenderer.on (/private/var/folders/z4/b157rzm93qb1g6fvrszxlhvr0000gn/T/AppTranslocation/F7CD8D13-C442-4794-A067-A3275C268586/d/Figma Plugins Desktop Injector.app/Contents/Resources/electron.asar/renderer/api/remote.js:285:21)
    at EventEmitter.emit (events.js:182:13)
```

---

Figma Plugins Desktop Injector 1.4.4
Electron 3.0.9
darwin 18.2.0
Locale: en-GB

**Comment by cdes** [comment]
Fixed in 1.6.0
https://github.com/cdes/figma-plugin-manager-desktop/releases/tag/v1.6.0
